/**
 * Generates Codex exec policy rules (.rules format) from CCBuddy's
 * PermissionGateRule[] configuration.
 *
 * Codex uses prefix_rule(pattern=[...], decision="allow"|"deny") syntax
 * with exact token matching — no regex support. We convert CCBuddy's
 * regex-based rules into conservative deny rules that block the most
 * common dangerous command prefixes.
 *
 * These rules serve as static safety when interactive permission gates
 * (canUseTool callback) are not available in the Codex backend.
 */

import { writeFileSync } from 'node:fs';
import type { PermissionGateRule } from '@ccbuddy/core';

interface CodexDenyRule {
  pattern: string[];
  comment: string;
}

/**
 * Convert a CCBuddy PermissionGateRule into one or more Codex deny rules.
 * Since Codex uses prefix matching (not regex), we expand common patterns
 * into their most likely concrete forms.
 */
function expandGateRule(rule: PermissionGateRule): CodexDenyRule[] {
  // Only Bash tool rules map to exec policy (file rules don't have CLI equivalents)
  if (rule.tool !== 'Bash' && rule.tool !== '*') return [];

  const rules: CodexDenyRule[] = [];

  switch (rule.name) {
    case 'destructive-rm':
      rules.push(
        { pattern: ['rm', '-rf'], comment: rule.description },
        { pattern: ['rm', '-fr'], comment: rule.description },
        { pattern: ['rm', '-r'], comment: rule.description },
      );
      break;

    case 'destructive-git':
      rules.push(
        { pattern: ['git', 'reset', '--hard'], comment: rule.description },
        { pattern: ['git', 'checkout', '.'], comment: rule.description },
        { pattern: ['git', 'clean', '-f'], comment: rule.description },
        { pattern: ['git', 'clean', '-fd'], comment: rule.description },
        { pattern: ['git', 'push', '--force'], comment: rule.description },
      );
      break;

    case 'launchctl':
      rules.push(
        { pattern: ['launchctl'], comment: rule.description },
      );
      break;

    case 'npm-publish':
      rules.push(
        { pattern: ['npm', 'publish'], comment: rule.description },
      );
      break;

    default:
      // For unknown rules, we can't generate prefix rules from regex.
      // Log a warning and skip.
      console.warn(`[codex-rules] Cannot convert rule "${rule.name}" (pattern: ${rule.pattern}) to Codex prefix rules — skipping`);
      break;
  }

  return rules;
}

/**
 * Generate a Codex .rules file content from CCBuddy permission gate rules.
 */
export function generateCodexRules(gateRules: PermissionGateRule[]): string {
  const lines: string[] = [
    '# Auto-generated by CCBuddy from permission gate rules.',
    '# These deny rules provide static safety for Codex sessions where',
    '# interactive permission approval (canUseTool) is not available.',
    '',
  ];

  for (const rule of gateRules) {
    const denyRules = expandGateRule(rule);
    for (const dr of denyRules) {
      const patternStr = dr.pattern.map(t => `"${t}"`).join(', ');
      lines.push(`# ${dr.comment}`);
      lines.push(`prefix_rule(pattern=[${patternStr}], decision="deny")`);
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * Write a Codex .rules file to disk.
 */
export function writeCodexRulesFile(path: string, gateRules: PermissionGateRule[]): void {
  const content = generateCodexRules(gateRules);
  writeFileSync(path, content, 'utf8');
}
